name: Validate YAML against JSON Schema
description: Validates a YAML file against a JSON Schema file.

inputs:
  schema:
    description: Path to the JSON Schema file
    required: true
  file:
    description: Path to the YAML file to validate
    required: true

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@e58605a9b6da7c637471fab8847a5e5a6b8df081  # v5

    - name: Validate YAML
      shell: bash
      env:
        SCHEMA: ${{ inputs.schema }}
        FILE: ${{ inputs.file }}
      run: |
        cd "${{ github.action_path }}"
        uv sync --frozen
        uv run validate.sh "$GITHUB_WORKSPACE/$SCHEMA" "$GITHUB_WORKSPACE/$FILE"
